[package]

name = "monte-carlo-test"
version = "0.0.1"
authors = ["Paho Lurie-Gregg <paho@paholg.com>"]

build = "build.rs"


[dependencies]
  time = "*"
  dimensioned = { path = "../dimensioned/" }
  typenum = "1.4.0"

[build-dependencies]
  tango = "*"

[[bin]]
  name = "v1"

[[bin]]
  name = "v2"

[[bin]]
  name = "v3"

[replace]
  "typenum:1.4.0" =  { git = "https://github.com/paholg/typenum/", branch = "trait-fns" }
